auth:
  jwksUrl: "https://centralidp.dev.demo.ftcpro.co/auth/realms/CX-Central/protocol/openid-connect/certs"
  issuerUrl: "https://centralidp.dev.demo.ftcpro.co/auth/realms/CX-Central"
  redirectUrl: "https://managed-identity-wallets.dev.demo.ftcpro.co/callback"
  realm: "CX-Central"
  role: "add_wallets"
  roleMappings: "create_wallets:add_wallets,view_wallets:view_wallets,update_wallets:update_wallets,delete_wallets:delete_wallets,view_wallet:view_wallet,update_wallet:update_wallet"
  resourceId: "Cl5-CX-Custodian"
datapoolUrl: "https://partners-pool.dev.demo.ftcpro.co"
datapool:
  url: "https://partners-pool.dev.demo.ftcpro.co"
  authUrl: "https://centralidp.dev.demo.ftcpro.co/auth/realms/CX-Central/protocol/openid-connect/token"
image:
  registry: "ghcr.io"
  tag: "latest-develop"
revocation:
  revocationServiceUrl: http://localhost:8086
  refreshHour: "3"
revocationService:
  port: "8086"
  httpAccessLog: true
  baseUrlForCredentialList: "https://managed-identity-wallets.dev.demo.catena-x.net/api/credentials/"
  minIssueInterval: "2"
  clientIssuanceApiUrl: "${SSI_SERVICE_URL:-http://localhost:8080}"
acapy:
  logLevel: "DEBUG"
  ledgerUrl: "https://indy-test.idu.network"
  endpointPort: "8000"
  endpointUrl: "https://managed-identity-wallets.dev.demo.ftcpro.co:8000/"
  adminPort: "11000"
  adminUrl: "http://localhost:11000"
  secret:
    name: "catenax-managed-identity-wallets-acapy-secrets"
    path: "managed-identity-wallets/data/dev/catenax-managed-identity-wallets-acapy-secrets"
  databaseHost: "ftcpro-postgresql-primary.postgres"
certificate:
  host: "managed-identity-wallets.dev.demo.ftcpro.co"
managedIdentityWallets:
  secret:
    name: "catenax-managed-identity-wallets-secrets"
    path: "managed-identity-wallets/data/dev/catenax-managed-identity-wallets-secrets"
postgresql:
  secret:
    name: "product-managed-identity-wallets-postgresql"
    path: "managed-identity-wallets/data/dev/postgres-managed-identity-wallets-secret-config"
acapypostgresql:
  secret:
    name: "product-managed-identity-wallets-acapy-postgresql"
    path: "managed-identity-wallets/data/dev/postgres-acapy-secret-config"