image:
  name: "catenax-ng/product-core-managed-identity-wallets_service"
  tag: "0.4.5"
allowEmptyPassword: "\"yes\""
db:
  jdbcDriver: "org.postgresql.Driver"
namespace: "managed-identity-wallets"
logging:
  exposed: "INFO"
wallet:
  baseWalletBpn: "BPNL000000000000"
revocation:
  refreshHour: "3"
revocationService:
  imageName: "registry.gitlab.com/gaia-x/data-infrastructure-federation-services/not/notarization-service/revocation"
  tag: "1.0.0-SNAPSHOT-quarkus-2.10.2.Final-java17"
  port: "8086"
  httpAccessLog: true
  minIssueInterval: "2"
acapy:
  imageName: "bcgovimages/aries-cloudagent"
  tag: "py36-1.16-1_0.7.4"
  ledgerUrl: "https://idu.cloudcompass.ca"
  label: "CatenaXIssuer"
  logLevel: "INFO"
  networkIdentifier: "idunion:test"
  databaseHost: "product-managed-identity-wallets-acapypostgresql"
acapypostgresql:
  enabled: true
  auth:
    existingSecret: "product-managed-identity-wallets-acapy-postgresql"
postgresql:
  enabled: true
  auth:
    existingSecret: "product-managed-identity-wallets-postgresql"
datapool:
  grantType: "client_credentials"
  scope: "openid"
  refreshHour: "23"
app:
  version: "0.4.0"
isLocal: false